# Generated by Django 4.0.3 on 2022-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myloginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
